### ISSUE TITLE
[UX] Zoom in on the map and characters

### ISSUE THREAD

**Issue by emilyclaudet** [emilyclaudet/family-game#11]
At the moment the game feels rather zoomed out and too tiny. 

To make it feel more engaging, I would recommend scaling up everything by 2x. Not sure the best way.

@cmclaudet thoughts?

**Comment by cmclaudet** [comment]
Easiest would be to just scale everything in the window by 2
https://love2d.org/wiki/love.graphics.scale

The images will look a bit blurry I think but for now it's probably ok. We can think about making all the assets twice as large if the blurriness is a problem

**Comment by emilyclaudet** [comment]
Solved here:
https://github.com/emilyclaudet/family-game/pull/10
